name: py-lesson-dev
channels:
- conda-forge
- default
dependencies:
- python>=3.9
- pip

# Lesson packages
- ipykernel
- jupyterlab
- pandas
- plotly

# Dev packages
- black
- jupyter_contrib_nbextensions
- jupyterlab-spellchecker

# Glosario dependencies
- pyyaml=5.3.1
- textdistance=4.2.0

# pip packages
- pip:
  - glosario
