---
title: Introducing pandas
---

::: questions ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

-   What is pandas?
-   Why use pandas for data analysis?

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::: objectives :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

-   Learn about the dataset we'll be working with
-   Import and display data from a CSV
-   Learn how pandas handles different types of data
-   Characterize data using info()

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

## Dataset description

The data we will be using is a time-series for a small mammal community
in southern Arizona. This is part of a project studying the effects of
rodents and ants on the plant community that has been running for almost
40 years. The rodents are sampled on a series of 24 plots, with
different experimental manipulations controlling which rodents are
allowed to access which plots.

This is a real dataset that has been used in over 100 publications.
We’ve simplified it for the workshop, but you can download the full
dataset and work with it using exactly the same tools we’ll learn
about today.

Questions

Let’s look at some of the cleaned spreadsheets you downloaded during
Setup to complete this challenge. You’ll need the following three
files:

-   surveys.csv
-   species.csv

### Answering questions using data

In order to answer the questions described above, we’ll need to do the
following basic data operations:

-   select subsets of the data (rows and columns)
-   group subsets of data
-   do math and other calculations
-   combine data across spreadsheets

In addition, we don’t want to do this manually! Instead of searching
for the right pieces of data ourselves, or clicking between
spreadsheets, or manually sorting columns, we want to make the computer
do the work.

In particular, we want to use a tool where it’s easy to repeat our
analysis in case our data changes. We also want to do all this searching
without actually modifying our source data.

## Why use pandas?

The Python Data Analysis Library, or pandas, is a Python library used to
work with dataframes. A dataframe is very similar to a spreadsheet,
consisting of rows and columns of data. It is a very common format for
representing scientific data and is likely to be very familiar to anyone
taking this course.

pandas offers the same advantages as any well-written library: It
creates a common codebase for working on a single task, in this case,
analyzing data. Some benefits of this approach include:

-   **Reliability:** Provides flexible, well-tested methods for
    reading, querying, aggregating, grouping, and plotting data
-   **Repeatability:** Repeat the same analyses when data is added
    or changed
-   **Speed:** Faster in many cases than coding our own functions in
    Python
-   **Reproducibility:** Document and share code in narrative form
    using tools like Jupyter notebooks
-   **Community:** Access a large, active community for help when we
    run into problems

## Importing data using pandas

Unlike the libraries in the Python Standard Library discussed in the
previous lesson, pandas is not part of the typical Python installation.
Once it has been installed, however, it can be accessed using the same
`import` command used to import the built-in libraries. By convention,
pandas is imported using the alias "pd". We can assign the alias using
the `as` keyword:

```{python, error=TRUE}
import pandas as pd
```

::: callout ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Why use an alias? We will refer to pandas many, many times when writing
a script, so it's useful to abbreviate the name and save some
keystrokes. But it's also a matter of consistency with the larger
community. Many of the core scientific Python libraries, including
pandas, recommend a specific alias, so most code you find online will
use those aliases as well.

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Now the pandas has been imported, we can access the function we need to
load data from a CSV, `pd.read_csv()`. The *call* has three parts:

-   The name (or in this case, alias) of the object that defines the
    function. This can be a library, alias, or any other object. It
    can also be omitted in some cases (for example, when using a
    function built into Python).
-   The name of the method we'd like to use
-   A set of parentheses that tells the function to run.

Many functions allow you to include both *arguments* and *keyword
arguments* (collectively called *parameters*) inside the parentheses
when calling the function. In this case, we will pass a single argument,
which is a string defining the path to the surveys.csv file:

```{python, error=TRUE}
pd.read_csv("data/surveys.csv")
```

A few things to observe about this table:

-   The unlabeled column on the far left is the row label
-   `pandas` has done a lot of work behind the scenes when reading
    the data, including:
    -   Assigning the row index as the row label
    -   Assigning each column a data type based on its contents
    -   Assigning certain cells the value NaN, which stands for
        "not a number" and is used to designate null values in
        the dataset. Here, those cells represent blank cells in
        the spreadsheet.

Most of this behavior can be controlled when the spreadsheet is first
read by using keyword arguments. A keyword argument is a named parameter
that you can use to control the behavior of a function. For example, to
force `pd.read_csv()` to use the existing record_id column as the row
label, use the `index_col` keyword argument:

```{python, error=TRUE}
pd.read_csv("data/surveys.csv", index_col="record_id")
```

Now record_id appears on the far left, indicating that `pandas` is using
that column as the row label.

::: challenge ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Run `help()` on the `pd.read_csv()` method (note that you should omit
the trailing parentheses). Alternatively, take a look at the [much
prettier documentation](https://pandas.pydata.org/pandas-
docs/stable/reference/api/pandas.read_csv.html) provided by the pandas
developers. Based on that information, answer the following questions:

1.  What parameter would you use to control how null values are
    interpreted?
2.  What values are interpreted as NaN by default?

::: solution :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

### Show me the solution to challenge 1

na_values

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::: solution :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

### Show me the solution to challenge 2

-   ""
-   "#N/A"
-   "#N/A N/A"
-   "#NA"
-   "-1.#IND"
-   "-1.#QNAN"
-   "-NaN"
-   "-nan"
-   "1.#IND"
-   "1.#QNAN"
-   "<NA>"
-   "N/A"
-   "NA"
-   "NULL"
-   "NaN"
-   "n/a"
-   "nan"
-   "null"

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

## Assigning to variables

We can assign the dataframe to a variable to make it easier to access.
As we saw in the previous lesson, we use a single equals sign to assign
an object to a variable. The variable name should be short and
descriptive. By convention, variables in Python use snake_case (that is,
lower case with individual words separated by underscores).

```{python, error=TRUE}
surveys = pd.read_csv("data/surveys.csv")
surveys
```

## Understanding data types in pandas

We can use the `info()` method to see how `pandas` interpreted each
column in the dataset. This method gives use the name, count, and data
type of each column and provides some information about the dataset as a
whole (for example, memory usage, which is helpful to know when working
with large datasets):

```{python, error=TRUE}
surveys.info()
```

Note that the data types used by pandas look a little different than the
ones used by Python itself. See the table below for the rough
equivalents.

### Data types in pandas

|Data Type|Description|Similar To|
|-|-|-|
|object|Character string or mixed|str|
|int64|Integer numerical (no decimal)|int|
|float64|Approximate numerical|float|
|bool|Stores True or False values|bool|
|datetime64|Stores date and time values|datetime.datetime|

## Saving a dataframe

When analyzing a dataset, we'll often want to save our work to a file.
The `to_csv()` method can be used to write a dataframe to a CSV:

```{python, error=TRUE}
surveys.to_csv("data/surveys_mod.csv", index=False)
```

But that is far from the only option -- `pandas` supports a variety of
file types for both reading and writing.
